spring:
  application:
    name: play-service
  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration
  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      region:
        static: us-east-1
      ssm:
        endpoint: http://localhost:4566
      s3:
        endpoint: http://localhost:4566
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5001}/${DB_NAME:metadata_db}
    username: ${DB_USERNAME:db_user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

app:
  cdn:
    enabled: true
    base-url: http://localhost:8080
  buckets:
    streams: streams-bucket

server:
  port: 20020
