spring:
  application:
    name: play-service
  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration
  cloud:
    aws:
      credentials:
        access-key: ${ACCESS_KEY:test}
        secret-key: ${SECRET_KEY:test}
      region:
        static: ${REGION:us-east-1}
      ssm:
        endpoint: ${SSM_ENDPOINT:http://localhost:4566}
      s3:
        endpoint: ${S3_ENDPOINT:http://localhost:4566}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5001}/${DB_NAME:metadata_db}
    username: ${DB_USERNAME:db_user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

app:
  cdn:
    enabled: true
    base-url: ${BASE_URL:http://localhost:8080}
  buckets:
    streams: ${STREAMS_BUCKET:streams-bucket}

server:
  port: 20020

logging:
  level:
    org:
      springframework:
        security: ${SECURITY_LOG_LEVEL:DEBUG}
        web: ${APP_LOG_LEVEL:INFO}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topic: service-logs