networks:
  streaming-platform-network:
    driver: bridge

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,cloudfront
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "../localstack-init:/etc/localstack/init/ready.d"
    networks:
      - streaming-platform-network
  
  metadata-db:
    image: postgres:latest
    container_name: metadata-db
    ports:
      - "5001:5432"
    env_file:
      - "../env/metadata.postgres.env"
    networks:
      - streaming-platform-network